/*
 * MenuMesa.java
 *
 * Created on 16 de Setembro de 2008, 00:14
 */

package sistemarestaurante;

import java.util.ArrayList;

/**
 *
 * @author  Usuário
 */
public class MenuMesaLivre extends javax.swing.JFrame {

    public int numControle;
    public InterfaceInternaCentral inter;
    private static MenuMesaLivre instancia = null;
    public ControleMesa controle;
    /** Creates new form MenuMesa */
    private MenuMesaLivre(int numControle, ControleMesa controle) {
        initComponents();
        //inter = InterfaceInternaCentral.getInstancia();
        this.numControle = numControle;
        this.controle = controle;
        System.out.println("numeroControle:" + controle.getNumControle());
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        statusMesaButtonGroup = new javax.swing.ButtonGroup();
        menuMesaPanel = new javax.swing.JPanel();
        mesaLivreLabel = new javax.swing.JLabel();
        numeroMesaLabel = new javax.swing.JLabel();
        numeroMesaTextField = new javax.swing.JTextField();
        reservarMesaButton = new javax.swing.JButton();
        tornarOcupadaButton = new javax.swing.JButton();
        okButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Mesa Livre");
        setResizable(false);

        menuMesaPanel.setBackground(new java.awt.Color(0, 51, 51));
        menuMesaPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 0), 2, true));

        mesaLivreLabel.setFont(new java.awt.Font("Tahoma", 1, 14));
        mesaLivreLabel.setForeground(new java.awt.Color(0, 153, 51));
        mesaLivreLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mesaLivreLabel.setText("A Mesa está Livre");

        numeroMesaLabel.setForeground(new java.awt.Color(255, 255, 255));
        numeroMesaLabel.setText("Número da Mesa:");

        numeroMesaTextField.setColumns(3);
        numeroMesaTextField.setEditable(false);
        numeroMesaTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        reservarMesaButton.setText("Reservar Mesa");
        reservarMesaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reservarMesaButtonActionPerformed(evt);
            }
        });

        tornarOcupadaButton.setText("Tornar Ocupada");
        tornarOcupadaButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tornarOcupadaButtonMouseClicked(evt);
            }
        });
        tornarOcupadaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tornarOcupadaButtonActionPerformed(evt);
            }
        });

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuMesaPanelLayout = new javax.swing.GroupLayout(menuMesaPanel);
        menuMesaPanel.setLayout(menuMesaPanelLayout);
        menuMesaPanelLayout.setHorizontalGroup(
            menuMesaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuMesaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menuMesaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(reservarMesaButton, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuMesaPanelLayout.createSequentialGroup()
                        .addComponent(numeroMesaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(numeroMesaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tornarOcupadaButton, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                    .addComponent(okButton, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(mesaLivreLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE))
                .addContainerGap())
        );
        menuMesaPanelLayout.setVerticalGroup(
            menuMesaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuMesaPanelLayout.createSequentialGroup()
                .addComponent(mesaLivreLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(menuMesaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numeroMesaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numeroMesaLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(reservarMesaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tornarOcupadaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(okButton)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuMesaPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuMesaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tornarOcupadaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tornarOcupadaButtonActionPerformed
        // TODO add your handling code here:
        //ControleMesaOcupada mesaOcupada = new ControleMesaOcupada(WIDTH, WIDTH, WIDTH, WIDTH, controleMesas, numControle, ocupacao)
        this.dispose();
        inter = InterfaceInternaCentral.getInstancia();
        inter.livreParaOcupada(controle);
        
}//GEN-LAST:event_tornarOcupadaButtonActionPerformed

private void reservarMesaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reservarMesaButtonActionPerformed
// TODO add your handling code here:
        this.dispose();
        inter = InterfaceInternaCentral.getInstancia();
        inter.livreParaReservada(controle);
}//GEN-LAST:event_reservarMesaButtonActionPerformed

private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
// TODO add your handling code here:
    this.dispose();
}//GEN-LAST:event_okButtonActionPerformed

private void tornarOcupadaButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tornarOcupadaButtonMouseClicked
    // TODO add your handling code here:
}//GEN-LAST:event_tornarOcupadaButtonMouseClicked

    /**
    * @param args the command line arguments
    */
    /*public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MenuMesaLivre livre;
                livre = new MenuMesaLivre(numControle);
                livre.setVisible(true);
            }
        });
    }*/

    public void setNumMesaTextField(String novoValor)
    {
        numeroMesaTextField.setText(novoValor);
    }
    
    public static MenuMesaLivre getInstancia(int numControle, ControleMesa controle)
    {
        
        if (instancia == null)
            instancia = new MenuMesaLivre(numControle, controle);
        instancia.setNumControle(numControle);
        instancia.setControle(controle);
        return instancia;
    }
    
    public void setNumControle(int novoValor)
    {
        numControle = novoValor;
    }
    
    public void setControle(ControleMesa novoControle)
    {
        controle = novoControle;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel menuMesaPanel;
    private javax.swing.JLabel mesaLivreLabel;
    private javax.swing.JLabel numeroMesaLabel;
    private javax.swing.JTextField numeroMesaTextField;
    private javax.swing.JButton okButton;
    private javax.swing.JButton reservarMesaButton;
    private javax.swing.ButtonGroup statusMesaButtonGroup;
    private javax.swing.JButton tornarOcupadaButton;
    // End of variables declaration//GEN-END:variables

}
