/*
 * menuReservas.java
 *
 * Created on 5 de Setembro de 2008, 09:20
 */

package sistemarestaurante;

import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.ListModel;

/**
 *
 * @author  edamiani
 */
public class MenuReservas extends javax.swing.JFrame {

    public ControleReservas controleReservas;
    /** Creates new form menuReservas */
    public MenuReservas() {
        super("SGR - Sistema Gerenciador de Restaurante (Menu de Reservas)");
        initComponents();

        controleReservas = new ControleReservas(this);
        //main();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        erroFaltaCamposDialog = new javax.swing.JDialog();
        erroFaltaCamposPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        menuReservasPanel = new javax.swing.JPanel();
        reservasLabel = new javax.swing.JLabel();
        dadosClientePanel = new javax.swing.JPanel();
        clienteLabel = new javax.swing.JLabel();
        nomeTextField = new javax.swing.JTextField();
        telefoneLabel = new javax.swing.JLabel();
        telefoneFormattedTextField = new javax.swing.JFormattedTextField();
        emailLabel = new javax.swing.JLabel();
        emailTextField = new javax.swing.JTextField();
        enderecoLabel = new javax.swing.JLabel();
        enderecoTextField = new javax.swing.JTextField();
        cidadeLabel = new javax.swing.JLabel();
        cidadeTextField = new javax.swing.JTextField();
        ufLabel = new javax.swing.JLabel();
        clientesCadastradosLabel = new javax.swing.JLabel();
        clientesCadastradosScrollPane = new javax.swing.JScrollPane();
        clientesCadastradosList = new javax.swing.JList();
        cadastrarClienteButton = new javax.swing.JButton();
        removerClienteButton = new javax.swing.JButton();
        clienteSelecionadoTextField = new javax.swing.JTextField();
        selecionarClienteButton = new javax.swing.JButton();
        clienteSelecionadoLabel = new javax.swing.JLabel();
        ufFormattedTextField = new javax.swing.JFormattedTextField();
        atualizarClienteButton = new javax.swing.JButton();
        dadoReservaPanel = new javax.swing.JPanel();
        numeroPessoasLabel = new javax.swing.JLabel();
        numeroPessoasTextField = new javax.swing.JTextField();
        tipoReservaLabel = new javax.swing.JLabel();
        tipoReservaComboBox = new javax.swing.JComboBox();
        dataLabel = new javax.swing.JLabel();
        dataFormattedTextField = new javax.swing.JFormattedTextField();
        horarioLabel = new javax.swing.JLabel();
        horarioFormattedTextField = new javax.swing.JFormattedTextField();
        informacoesAdicionaisLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        informacoesAdicionaistextArea = new javax.swing.JTextArea();
        listaReservasPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaReservasList = new javax.swing.JList();
        removerReservaButton = new javax.swing.JButton();
        atualizarReservaButton = new javax.swing.JButton();
        okButton = new javax.swing.JButton();
        asteriscoLabel = new javax.swing.JLabel();
        cadastraAtualizarReservaButton = new javax.swing.JButton();

        erroFaltaCamposDialog.setTitle("ERRO!");
        erroFaltaCamposDialog.setResizable(false);

        erroFaltaCamposPanel.setBackground(new java.awt.Color(204, 204, 255));
        erroFaltaCamposPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel1.setOpaque(true);

        javax.swing.GroupLayout erroFaltaCamposPanelLayout = new javax.swing.GroupLayout(erroFaltaCamposPanel);
        erroFaltaCamposPanel.setLayout(erroFaltaCamposPanelLayout);
        erroFaltaCamposPanelLayout.setHorizontalGroup(
            erroFaltaCamposPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(erroFaltaCamposPanelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(310, Short.MAX_VALUE))
        );
        erroFaltaCamposPanelLayout.setVerticalGroup(
            erroFaltaCamposPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(erroFaltaCamposPanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout erroFaltaCamposDialogLayout = new javax.swing.GroupLayout(erroFaltaCamposDialog.getContentPane());
        erroFaltaCamposDialog.getContentPane().setLayout(erroFaltaCamposDialogLayout);
        erroFaltaCamposDialogLayout.setHorizontalGroup(
            erroFaltaCamposDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(erroFaltaCamposPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        erroFaltaCamposDialogLayout.setVerticalGroup(
            erroFaltaCamposDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(erroFaltaCamposPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SGR - Menu de Gerenciamento de Reservas do Restaurante");
        setResizable(false);

        menuReservasPanel.setBackground(new java.awt.Color(0, 51, 51));
        menuReservasPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 153, 0), 2, true));
        menuReservasPanel.setName("Menu de Reservas"); // NOI18N

        reservasLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        reservasLabel.setForeground(new java.awt.Color(255, 255, 255));
        reservasLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        reservasLabel.setText("Gerenciamento de Reservas do Restaurante");

        dadosClientePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 153, 0), 1, true), "Dados do Cliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 12), new java.awt.Color(51, 153, 0))); // NOI18N
        dadosClientePanel.setForeground(new java.awt.Color(51, 153, 0));
        dadosClientePanel.setOpaque(false);

        clienteLabel.setForeground(new java.awt.Color(255, 255, 255));
        clienteLabel.setText("Nome*:");

        nomeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeTextFieldActionPerformed(evt);
            }
        });

        telefoneLabel.setForeground(new java.awt.Color(255, 255, 255));
        telefoneLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        telefoneLabel.setText("Telefone*: ");

        telefoneFormattedTextField.setColumns(7);
        try {
            telefoneFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        telefoneFormattedTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        telefoneFormattedTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefoneFormattedTextFieldActionPerformed(evt);
            }
        });

        emailLabel.setForeground(new java.awt.Color(255, 255, 255));
        emailLabel.setText("E-mail: ");

        enderecoLabel.setForeground(new java.awt.Color(255, 255, 255));
        enderecoLabel.setText("Endereço:");

        cidadeLabel.setForeground(new java.awt.Color(255, 255, 255));
        cidadeLabel.setText("Cidade:");

        cidadeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cidadeTextFieldActionPerformed(evt);
            }
        });

        ufLabel.setForeground(new java.awt.Color(255, 255, 255));
        ufLabel.setText("UF:");

        clientesCadastradosLabel.setForeground(new java.awt.Color(255, 255, 255));
        clientesCadastradosLabel.setText("Clientes Cadastrados:");

        clientesCadastradosList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                clientesCadastradosListValueChanged(evt);
            }
        });
        clientesCadastradosScrollPane.setViewportView(clientesCadastradosList);

        cadastrarClienteButton.setText("Cadastrar");
        cadastrarClienteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarClienteButtonActionPerformed(evt);
            }
        });

        removerClienteButton.setText("Remover");
        removerClienteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerClienteButtonActionPerformed(evt);
            }
        });

        clienteSelecionadoTextField.setEditable(false);

        selecionarClienteButton.setText("Selecionar");
        selecionarClienteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selecionarClienteButtonActionPerformed(evt);
            }
        });

        clienteSelecionadoLabel.setForeground(new java.awt.Color(255, 255, 255));
        clienteSelecionadoLabel.setText("Cliente Selecionado para a Reserva:");

        ufFormattedTextField.setColumns(2);

        atualizarClienteButton.setText("Atualizar");
        atualizarClienteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarClienteButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dadosClientePanelLayout = new javax.swing.GroupLayout(dadosClientePanel);
        dadosClientePanel.setLayout(dadosClientePanelLayout);
        dadosClientePanelLayout.setHorizontalGroup(
            dadosClientePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dadosClientePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dadosClientePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, dadosClientePanelLayout.createSequentialGroup()
                        .addGroup(dadosClientePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cidadeLabel)
                            .addComponent(clienteLabel)
                            .addComponent(enderecoLabel)
                            .addComponent(emailLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(dadosClientePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(enderecoTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
                            .addComponent(nomeTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
                            .addGroup(dadosClientePanelLayout.createSequentialGroup()
                                .addComponent(cidadeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ufLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ufFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7)
                                .addComponent(telefoneLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(telefoneFormattedTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE))
                            .addComponent(emailTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)))
                    .addComponent(clientesCadastradosLabel, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(clientesCadastradosScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE)
                    .addComponent(clienteSelecionadoLabel, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(clienteSelecionadoTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE)
                    .addGroup(dadosClientePanelLayout.createSequentialGroup()
                        .addComponent(selecionarClienteButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                        .addComponent(cadastrarClienteButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(atualizarClienteButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(removerClienteButton)))
                .addContainerGap())
        );
        dadosClientePanelLayout.setVerticalGroup(
            dadosClientePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dadosClientePanelLayout.createSequentialGroup()
                .addGroup(dadosClientePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, Short.MAX_VALUE)
                    .addComponent(clienteLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE))
                .addGap(7, 7, 7)
                .addGroup(dadosClientePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enderecoLabel)
                    .addComponent(enderecoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dadosClientePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cidadeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ufLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(telefoneFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(telefoneLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cidadeLabel)
                    .addComponent(ufFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dadosClientePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(clientesCadastradosLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clientesCadastradosScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dadosClientePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(removerClienteButton)
                    .addComponent(selecionarClienteButton)
                    .addComponent(atualizarClienteButton)
                    .addComponent(cadastrarClienteButton))
                .addGap(7, 7, 7)
                .addComponent(clienteSelecionadoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clienteSelecionadoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        dadoReservaPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 153, 0), 1, true), "Dados da Reserva", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 12), new java.awt.Color(51, 153, 0))); // NOI18N
        dadoReservaPanel.setOpaque(false);

        numeroPessoasLabel.setForeground(new java.awt.Color(255, 255, 255));
        numeroPessoasLabel.setText("Número de Pessoas *:");

        numeroPessoasTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        numeroPessoasTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeroPessoasTextFieldActionPerformed(evt);
            }
        });

        tipoReservaLabel.setForeground(new java.awt.Color(255, 255, 255));
        tipoReservaLabel.setText("Tipo de Reserva *:");

        tipoReservaComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "Almoço", "Jantar", "Evento" }));

        dataLabel.setForeground(new java.awt.Color(255, 255, 255));
        dataLabel.setText("Data da Reserva *:");

        dataFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        dataFormattedTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        dataFormattedTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataFormattedTextFieldActionPerformed(evt);
            }
        });

        horarioLabel.setForeground(new java.awt.Color(255, 255, 255));
        horarioLabel.setText("Horário da Reserva *:");

        horarioFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getTimeInstance(java.text.DateFormat.SHORT))));
        horarioFormattedTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        horarioFormattedTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                horarioFormattedTextFieldActionPerformed(evt);
            }
        });

        informacoesAdicionaisLabel.setForeground(new java.awt.Color(255, 255, 255));
        informacoesAdicionaisLabel.setText("Informações Adicionais:");

        informacoesAdicionaistextArea.setColumns(20);
        informacoesAdicionaistextArea.setLineWrap(true);
        informacoesAdicionaistextArea.setRows(5);
        informacoesAdicionaistextArea.setWrapStyleWord(true);
        jScrollPane2.setViewportView(informacoesAdicionaistextArea);

        javax.swing.GroupLayout dadoReservaPanelLayout = new javax.swing.GroupLayout(dadoReservaPanel);
        dadoReservaPanel.setLayout(dadoReservaPanelLayout);
        dadoReservaPanelLayout.setHorizontalGroup(
            dadoReservaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dadoReservaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dadoReservaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dadoReservaPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addContainerGap())
                    .addGroup(dadoReservaPanelLayout.createSequentialGroup()
                        .addGroup(dadoReservaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(dataLabel)
                            .addComponent(tipoReservaLabel)
                            .addComponent(numeroPessoasLabel)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, dadoReservaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(informacoesAdicionaisLabel)
                                .addComponent(horarioLabel)))
                        .addGap(10, 10, 10)
                        .addGroup(dadoReservaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(dadoReservaPanelLayout.createSequentialGroup()
                                .addGroup(dadoReservaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(horarioFormattedTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(dataFormattedTextField)
                                    .addComponent(tipoReservaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28))
                            .addGroup(dadoReservaPanelLayout.createSequentialGroup()
                                .addComponent(numeroPessoasTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))))
        );
        dadoReservaPanelLayout.setVerticalGroup(
            dadoReservaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dadoReservaPanelLayout.createSequentialGroup()
                .addGroup(dadoReservaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numeroPessoasLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numeroPessoasTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dadoReservaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tipoReservaLabel)
                    .addComponent(tipoReservaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dadoReservaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dataFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dataLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(dadoReservaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(horarioFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(horarioLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(informacoesAdicionaisLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                .addContainerGap())
        );

        listaReservasPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 153, 0), 1, true), "Lista de Reservas Efetuadas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 12), new java.awt.Color(51, 153, 0))); // NOI18N
        listaReservasPanel.setOpaque(false);

        listaReservasList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listaReservasListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listaReservasList);

        removerReservaButton.setText("Remover");
        removerReservaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerReservaButtonActionPerformed(evt);
            }
        });

        atualizarReservaButton.setText("Atualizar");
        atualizarReservaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarReservaButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout listaReservasPanelLayout = new javax.swing.GroupLayout(listaReservasPanel);
        listaReservasPanel.setLayout(listaReservasPanelLayout);
        listaReservasPanelLayout.setHorizontalGroup(
            listaReservasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listaReservasPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(listaReservasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, listaReservasPanelLayout.createSequentialGroup()
                        .addComponent(atualizarReservaButton)
                        .addGap(4, 4, 4)
                        .addComponent(removerReservaButton)))
                .addContainerGap())
        );
        listaReservasPanelLayout.setVerticalGroup(
            listaReservasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, listaReservasPanelLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(listaReservasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(atualizarReservaButton)
                    .addComponent(removerReservaButton))
                .addContainerGap())
        );

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        asteriscoLabel.setForeground(new java.awt.Color(255, 255, 255));
        asteriscoLabel.setText("(*) Campos de Preenchimento Obrigatório.");

        cadastraAtualizarReservaButton.setText("Cadastrar Reserva");
        cadastraAtualizarReservaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastraAtualizarReservaButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuReservasPanelLayout = new javax.swing.GroupLayout(menuReservasPanel);
        menuReservasPanel.setLayout(menuReservasPanelLayout);
        menuReservasPanelLayout.setHorizontalGroup(
            menuReservasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuReservasPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menuReservasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(reservasLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(menuReservasPanelLayout.createSequentialGroup()
                        .addComponent(dadosClientePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(menuReservasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cadastraAtualizarReservaButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dadoReservaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(listaReservasPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuReservasPanelLayout.createSequentialGroup()
                        .addComponent(asteriscoLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        menuReservasPanelLayout.setVerticalGroup(
            menuReservasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuReservasPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(reservasLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(menuReservasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuReservasPanelLayout.createSequentialGroup()
                        .addComponent(dadoReservaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cadastraAtualizarReservaButton, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE))
                    .addComponent(dadosClientePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(listaReservasPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(menuReservasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(asteriscoLabel))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuReservasPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuReservasPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void horarioFormattedTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_horarioFormattedTextFieldActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_horarioFormattedTextFieldActionPerformed

private void dataFormattedTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataFormattedTextFieldActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_dataFormattedTextFieldActionPerformed

private void numeroPessoasTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeroPessoasTextFieldActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_numeroPessoasTextFieldActionPerformed

private void cidadeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cidadeTextFieldActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_cidadeTextFieldActionPerformed

private void telefoneFormattedTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefoneFormattedTextFieldActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_telefoneFormattedTextFieldActionPerformed

private void nomeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeTextFieldActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_nomeTextFieldActionPerformed

private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
// TODO add your handling code here:
    //show(false);
    dispose();
}//GEN-LAST:event_okButtonActionPerformed

private void cadastrarClienteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarClienteButtonActionPerformed
    // TODO add your handling code here:
     controleReservas.validaDadosCliente();
}//GEN-LAST:event_cadastrarClienteButtonActionPerformed

private void cadastraAtualizarReservaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastraAtualizarReservaButtonActionPerformed
    controleReservas.validaDadosReserva();
}//GEN-LAST:event_cadastraAtualizarReservaButtonActionPerformed

private void removerClienteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerClienteButtonActionPerformed
    // TODO add your handling code here:
    if (!clientesCadastradosList.isSelectionEmpty())
    {
        int option = JOptionPane.showConfirmDialog(null, "Aviso: Você está prestes a remover um registro de Cliente!" +
                " Deseja remover assim mesmo?", "Cuidado!", JOptionPane.YES_NO_OPTION, 
            JOptionPane.WARNING_MESSAGE);
        if (option == 0)
        {
            controleReservas.removeReserva(new Reserva(0, null, null, null, null,
                    new Cliente(getNomeCliente(),
                    getEnderecoCliente(), getCidadeCliente(), getUfCliente(),
                    getTelefoneCliente(), getEmailCliente())));
            controleReservas.removeCliente(clientesCadastradosList.getSelectedValue().toString());
        }
    }
}//GEN-LAST:event_removerClienteButtonActionPerformed

private void clientesCadastradosListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_clientesCadastradosListValueChanged
// TODO add your handling code here:
    if (!clientesCadastradosList.isSelectionEmpty())
        controleReservas.buscaCamposCliente(clientesCadastradosList.getSelectedValue().toString());
        nomeTextField.setEditable(true);
        enderecoTextField.setEditable(true);
        cidadeTextField.setEditable(true);
        ufFormattedTextField.setEditable(true);
        telefoneFormattedTextField.setEditable(true);
        emailTextField.setEditable(true);
}//GEN-LAST:event_clientesCadastradosListValueChanged

private void selecionarClienteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selecionarClienteButtonActionPerformed
    if (!clientesCadastradosList.isSelectionEmpty())
        clienteSelecionadoTextField.setText(clientesCadastradosList.getSelectedValue().toString());
}//GEN-LAST:event_selecionarClienteButtonActionPerformed

private void removerReservaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerReservaButtonActionPerformed
// TODO add your handling code here:
    if (!listaReservasList.isSelectionEmpty())
    {
        int option = JOptionPane.showConfirmDialog(null, "Aviso: Você está prestes a remover um registro de Reserva!" +
                "Deseja remover assim mesmo?", "Cuidado!", JOptionPane.YES_NO_OPTION, 
            JOptionPane.WARNING_MESSAGE);
        if (option == 0)
        controleReservas.removeReserva(listaReservasList.getSelectedValue().toString());
    }
}//GEN-LAST:event_removerReservaButtonActionPerformed

private void listaReservasListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listaReservasListValueChanged
// TODO add your handling code here:
    if (!listaReservasList.isSelectionEmpty())
    {
        controleReservas.buscaCamposReserva(listaReservasList.getSelectedValue().toString());
        nomeTextField.setEditable(false);
        enderecoTextField.setEditable(false);
        cidadeTextField.setEditable(false);
        ufFormattedTextField.setEditable(false);
        telefoneFormattedTextField.setEditable(false);
        emailTextField.setEditable(false);
    }
}//GEN-LAST:event_listaReservasListValueChanged

private void atualizarClienteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarClienteButtonActionPerformed
    // TODO add your handling code here:
    if (!clientesCadastradosList.isSelectionEmpty())
    {
        controleReservas.atualizaCliente(new Cliente(getNomeCliente(), getEnderecoCliente(),
                getCidadeCliente(), getUfCliente(), getTelefoneCliente(), getEmailCliente()),
                clientesCadastradosList.getSelectedValue().toString());
    }
}//GEN-LAST:event_atualizarClienteButtonActionPerformed

private void atualizarReservaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarReservaButtonActionPerformed
    // TODO add your handling code here:
    if (!listaReservasList.isSelectionEmpty())
    {
        controleReservas.atualizaReserva(new Reserva(getNumeroPessoasReserva(), 
                getTipoReserva(), getDataReserva(), getHorarioReserva(), 
                getInformacoesReserva(), new Cliente(getNomeCliente(), getEnderecoCliente(),
                getCidadeCliente(), getUfCliente(), getTelefoneCliente(), getEmailCliente())),
                listaReservasList.getSelectedValue().toString());
    }
}//GEN-LAST:event_atualizarReservaButtonActionPerformed

public String getNomeCliente()
{
     return nomeTextField.getText();
}

public void setNomeCliente(String novoNome)
{
    nomeTextField.setText(novoNome);
}

public String getEnderecoCliente()
{
     return enderecoTextField.getText();
}

public void setEnderecoCliente(String novoEndereco)
{
    enderecoTextField.setText(novoEndereco);
}

public String getCidadeCliente()
{
    return cidadeTextField.getText();
}

public void setCidadeCliente(String novaCidade)
{
    cidadeTextField.setText(novaCidade);
}

public String getUfCliente()
{
    return ufFormattedTextField.getText();
}

public void setUfCliente(String novoUf)
{
    ufFormattedTextField.setText(novoUf);
}

public String getTelefoneCliente()
{
    return telefoneFormattedTextField.getText();
}

public void setTelefoneCliente(String novoTelefone)
{
    telefoneFormattedTextField.setText(novoTelefone);
}

public String getEmailCliente()
{
    return emailTextField.getText();
}

public void setEmailCliente(String novoEmail)
{
    emailTextField.setText(novoEmail);
}

public String getNomeClienteSelecionado()
{
    return clienteSelecionadoTextField.getText();
}

public void setNomeClienteSelecionado(String novoNome)
{
    clienteSelecionadoTextField.setText(novoNome);
}

public int getNumeroPessoasReserva()
{
    if (numeroPessoasTextField.getText().equals(""))
        return 0;
    return Integer.parseInt(numeroPessoasTextField.getText());
     
}

public void setNumeroPessoasReserva(String novoNumero)
{
    numeroPessoasTextField.setText(novoNumero);
}

public String getTipoReserva()
{
    return tipoReservaComboBox.getSelectedItem().toString();
}

public void setTipoReserva(String novoTipo)
{
    tipoReservaComboBox.setSelectedItem(novoTipo);
}

public String getDataReserva()
{
    return dataFormattedTextField.getText();
}

public void setDataReserva(String novaData)
{
    dataFormattedTextField.setText(novaData);
}

public String getHorarioReserva()
{
    return horarioFormattedTextField.getText();
}

public void setHorarioReserva(String novoHorario)
{
    horarioFormattedTextField.setText(novoHorario);
}

public String getInformacoesReserva()
{
    return informacoesAdicionaistextArea.getText();
}

public void setInformacoesReserva(String novaInfo)
{
    informacoesAdicionaistextArea.setText(novaInfo);
}

public void setListaClientesCadastrados(ListModel list)
{
    clientesCadastradosList.setModel(list);
}

public void setListaReservasCadastradas(ListModel list)
{
    listaReservasList.setModel(list);
}
    

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuReservas().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel asteriscoLabel;
    private javax.swing.JButton atualizarClienteButton;
    private javax.swing.JButton atualizarReservaButton;
    private javax.swing.JButton cadastraAtualizarReservaButton;
    private javax.swing.JButton cadastrarClienteButton;
    private javax.swing.JLabel cidadeLabel;
    private javax.swing.JTextField cidadeTextField;
    private javax.swing.JLabel clienteLabel;
    private javax.swing.JLabel clienteSelecionadoLabel;
    private javax.swing.JTextField clienteSelecionadoTextField;
    private javax.swing.JLabel clientesCadastradosLabel;
    private javax.swing.JList clientesCadastradosList;
    private javax.swing.JScrollPane clientesCadastradosScrollPane;
    private javax.swing.JPanel dadoReservaPanel;
    private javax.swing.JPanel dadosClientePanel;
    private javax.swing.JFormattedTextField dataFormattedTextField;
    private javax.swing.JLabel dataLabel;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JLabel enderecoLabel;
    private javax.swing.JTextField enderecoTextField;
    private javax.swing.JDialog erroFaltaCamposDialog;
    private javax.swing.JPanel erroFaltaCamposPanel;
    private javax.swing.JFormattedTextField horarioFormattedTextField;
    private javax.swing.JLabel horarioLabel;
    private javax.swing.JLabel informacoesAdicionaisLabel;
    private javax.swing.JTextArea informacoesAdicionaistextArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList listaReservasList;
    private javax.swing.JPanel listaReservasPanel;
    private javax.swing.JPanel menuReservasPanel;
    private javax.swing.JTextField nomeTextField;
    private javax.swing.JLabel numeroPessoasLabel;
    private javax.swing.JTextField numeroPessoasTextField;
    private javax.swing.JButton okButton;
    private javax.swing.JButton removerClienteButton;
    private javax.swing.JButton removerReservaButton;
    private javax.swing.JLabel reservasLabel;
    private javax.swing.JButton selecionarClienteButton;
    private javax.swing.JFormattedTextField telefoneFormattedTextField;
    private javax.swing.JLabel telefoneLabel;
    private javax.swing.JComboBox tipoReservaComboBox;
    private javax.swing.JLabel tipoReservaLabel;
    private javax.swing.JFormattedTextField ufFormattedTextField;
    private javax.swing.JLabel ufLabel;
    // End of variables declaration//GEN-END:variables
    
}
