/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MenuCadastroFuncionario.java
 *
 * Created on 12/09/2008, 09:22:46
 */

package sistemarestaurante;

import java.awt.Frame;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author edamiani
 */
public class MenuCadastroFuncionario extends javax.swing.JFrame {

    private ControleFuncionarios controleFuncionarios;
    /** Creates new form MenuCadastroFuncionario */
    public MenuCadastroFuncionario() {
        initComponents();
        
        controleFuncionarios = new ControleFuncionarios(this);
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        menuCadastroFuncionarioPanel = new javax.swing.JPanel();
        cadastroFuncionarioLabel = new javax.swing.JLabel();
        dadosFuncionarioPanel = new javax.swing.JPanel();
        nomeLabel = new javax.swing.JLabel();
        nomeTextField = new javax.swing.JTextField();
        rgLabel = new javax.swing.JLabel();
        rgFormattedTextField = new javax.swing.JFormattedTextField();
        cpfLabel = new javax.swing.JLabel();
        cpfFormattedTextField = new javax.swing.JFormattedTextField();
        estadoCivilComboBox = new javax.swing.JComboBox();
        estadoCivilLabel = new javax.swing.JLabel();
        enderecoLabel = new javax.swing.JLabel();
        enderecoTextField = new javax.swing.JTextField();
        criarCadastroButton = new javax.swing.JButton();
        telefoneLabel = new javax.swing.JLabel();
        telefoneFormattedTextField = new javax.swing.JFormattedTextField();
        cargoLabel = new javax.swing.JLabel();
        cargoComboBox = new javax.swing.JComboBox();
        salarioLabel = new javax.swing.JLabel();
        salarioFormattedTextField = new javax.swing.JFormattedTextField();
        painelCadastrosEfetuadosPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaCadastrosList = new javax.swing.JList();
        atualizarButton = new javax.swing.JButton();
        removerButton = new javax.swing.JButton();
        okButton = new javax.swing.JButton();
        camposPreenchidosLabel = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SGR - Menu de Cadastro de Funcionários");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        menuCadastroFuncionarioPanel.setBackground(new java.awt.Color(0, 51, 51));
        menuCadastroFuncionarioPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 0), 2, true));

        cadastroFuncionarioLabel.setFont(new java.awt.Font("Tahoma", 1, 18));
        cadastroFuncionarioLabel.setForeground(new java.awt.Color(255, 255, 255));
        cadastroFuncionarioLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cadastroFuncionarioLabel.setText("Cadastro de Funcionários");

        dadosFuncionarioPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 0), 1, true), "Dados do Funcionário", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 204, 0))); // NOI18N
        dadosFuncionarioPanel.setForeground(new java.awt.Color(51, 153, 0));
        dadosFuncionarioPanel.setOpaque(false);

        nomeLabel.setForeground(new java.awt.Color(255, 255, 255));
        nomeLabel.setText("Nome:");

        rgLabel.setForeground(new java.awt.Color(255, 255, 255));
        rgLabel.setText("RG:");

        rgFormattedTextField.setColumns(10);
        try {
            rgFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        rgFormattedTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        rgFormattedTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rgFormattedTextFieldActionPerformed(evt);
            }
        });

        cpfLabel.setForeground(new java.awt.Color(255, 255, 255));
        cpfLabel.setText("CPF:");

        cpfFormattedTextField.setColumns(14);
        try {
            cpfFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        cpfFormattedTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        estadoCivilComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "Casado", "Solteiro" }));

        estadoCivilLabel.setForeground(new java.awt.Color(255, 255, 255));
        estadoCivilLabel.setText("Estado Civil:");

        enderecoLabel.setForeground(new java.awt.Color(255, 255, 255));
        enderecoLabel.setText("Endereço:");

        criarCadastroButton.setText("Criar Cadastro");
        criarCadastroButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                criarCadastroButtonActionPerformed(evt);
            }
        });

        telefoneLabel.setForeground(new java.awt.Color(255, 255, 255));
        telefoneLabel.setText("Telefone:");

        telefoneFormattedTextField.setColumns(7);
        try {
            telefoneFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        telefoneFormattedTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        cargoLabel.setForeground(new java.awt.Color(255, 255, 255));
        cargoLabel.setText("Cargo no Restaurante:");

        cargoComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cozinheira(o)", "Garçom/Garçonete", "Gerente", "Faxineira(o)" }));

        salarioLabel.setForeground(new java.awt.Color(255, 255, 255));
        salarioLabel.setText("Salário:");

        salarioFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));

        javax.swing.GroupLayout dadosFuncionarioPanelLayout = new javax.swing.GroupLayout(dadosFuncionarioPanel);
        dadosFuncionarioPanel.setLayout(dadosFuncionarioPanelLayout);
        dadosFuncionarioPanelLayout.setHorizontalGroup(
            dadosFuncionarioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dadosFuncionarioPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(dadosFuncionarioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(enderecoLabel)
                    .addComponent(rgLabel)
                    .addComponent(nomeLabel)
                    .addComponent(telefoneLabel)
                    .addComponent(salarioLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dadosFuncionarioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nomeTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE)
                    .addComponent(enderecoTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dadosFuncionarioPanelLayout.createSequentialGroup()
                        .addGroup(dadosFuncionarioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(salarioFormattedTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                            .addGroup(dadosFuncionarioPanelLayout.createSequentialGroup()
                                .addComponent(rgFormattedTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cpfLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(telefoneFormattedTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(dadosFuncionarioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, dadosFuncionarioPanelLayout.createSequentialGroup()
                                .addComponent(cpfFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(estadoCivilLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(estadoCivilComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, dadosFuncionarioPanelLayout.createSequentialGroup()
                                .addComponent(cargoLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cargoComboBox, 0, 145, Short.MAX_VALUE))
                            .addComponent(criarCadastroButton))))
                .addContainerGap())
        );
        dadosFuncionarioPanelLayout.setVerticalGroup(
            dadosFuncionarioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dadosFuncionarioPanelLayout.createSequentialGroup()
                .addGroup(dadosFuncionarioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dadosFuncionarioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enderecoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enderecoLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dadosFuncionarioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rgFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cpfLabel)
                    .addComponent(cpfFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(estadoCivilComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(estadoCivilLabel)
                    .addComponent(rgLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dadosFuncionarioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telefoneFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cargoLabel)
                    .addComponent(cargoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(telefoneLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dadosFuncionarioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salarioFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(criarCadastroButton)
                    .addComponent(salarioLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        painelCadastrosEfetuadosPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 0), 1, true), "Cadastros Efetuados", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 204, 0))); // NOI18N
        painelCadastrosEfetuadosPanel.setOpaque(false);

        listaCadastrosList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listaCadastrosListValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(listaCadastrosList);

        atualizarButton.setText("Atualizar");
        atualizarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarButtonActionPerformed(evt);
            }
        });

        removerButton.setText("Remover");
        removerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelCadastrosEfetuadosPanelLayout = new javax.swing.GroupLayout(painelCadastrosEfetuadosPanel);
        painelCadastrosEfetuadosPanel.setLayout(painelCadastrosEfetuadosPanelLayout);
        painelCadastrosEfetuadosPanelLayout.setHorizontalGroup(
            painelCadastrosEfetuadosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCadastrosEfetuadosPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelCadastrosEfetuadosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 429, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelCadastrosEfetuadosPanelLayout.createSequentialGroup()
                        .addComponent(atualizarButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(removerButton)))
                .addContainerGap())
        );
        painelCadastrosEfetuadosPanelLayout.setVerticalGroup(
            painelCadastrosEfetuadosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCadastrosEfetuadosPanelLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(painelCadastrosEfetuadosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(removerButton)
                    .addComponent(atualizarButton))
                .addGap(6, 6, 6))
        );

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        camposPreenchidosLabel.setForeground(new java.awt.Color(255, 255, 255));
        camposPreenchidosLabel.setText("Todos os campos devem ser preenchidos.");

        javax.swing.GroupLayout menuCadastroFuncionarioPanelLayout = new javax.swing.GroupLayout(menuCadastroFuncionarioPanel);
        menuCadastroFuncionarioPanel.setLayout(menuCadastroFuncionarioPanelLayout);
        menuCadastroFuncionarioPanelLayout.setHorizontalGroup(
            menuCadastroFuncionarioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuCadastroFuncionarioPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menuCadastroFuncionarioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dadosFuncionarioPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cadastroFuncionarioLabel)
                    .addComponent(painelCadastrosEfetuadosPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuCadastroFuncionarioPanelLayout.createSequentialGroup()
                        .addComponent(camposPreenchidosLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 183, Short.MAX_VALUE)
                        .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        menuCadastroFuncionarioPanelLayout.setVerticalGroup(
            menuCadastroFuncionarioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuCadastroFuncionarioPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cadastroFuncionarioLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dadosFuncionarioPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelCadastrosEfetuadosPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(menuCadastroFuncionarioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(camposPreenchidosLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuCadastroFuncionarioPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuCadastroFuncionarioPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rgFormattedTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rgFormattedTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rgFormattedTextFieldActionPerformed

    private void criarCadastroButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_criarCadastroButtonActionPerformed
// TODO add your handling code here:
    controleFuncionarios.validaDadosFuncionario();
}//GEN-LAST:event_criarCadastroButtonActionPerformed

private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
    // TODO add your handling code here:
    dispose();
}//GEN-LAST:event_okButtonActionPerformed

private void removerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerButtonActionPerformed
    // TODO add your handling code here:
    if (!listaCadastrosList.isSelectionEmpty())
    {
        int option = JOptionPane.showConfirmDialog(null, "Aviso: Você está prestes a remover um registro de Funcionário!" +
                "Deseja remover assim mesmo?", "Cuidado!", JOptionPane.YES_NO_OPTION, 
            JOptionPane.WARNING_MESSAGE);
        if (option == 0)
        controleFuncionarios.removeFuncionario(listaCadastrosList.getSelectedValue().toString());
    }
}//GEN-LAST:event_removerButtonActionPerformed

private void listaCadastrosListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listaCadastrosListValueChanged
// TODO add your handling code here:
    if (!listaCadastrosList.isSelectionEmpty())
    {
        controleFuncionarios.buscaCamposFuncionario(listaCadastrosList.getSelectedValue().toString());
    }
}//GEN-LAST:event_listaCadastrosListValueChanged

private void atualizarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarButtonActionPerformed
    // TODO add your handling code here:
    if (!listaCadastrosList.isSelectionEmpty())
    {
        controleFuncionarios.atualizaFuncionario(new Funcionario(getNome(), getEndereco(),
                getRg(), getCpf(), getEstadoCivil(), getTelefone(), getCargo(), getSalario()),
                listaCadastrosList.getSelectedValue().toString());
    }
}//GEN-LAST:event_atualizarButtonActionPerformed

public String getNome()
{
    return nomeTextField.getText();
}

public void setNome(String novoNome)
{
    nomeTextField.setText(novoNome);
}

public String getEndereco()
{
    return enderecoTextField.getText();
}

public void setEndereco(String novoEndereco)
{
    enderecoTextField.setText(novoEndereco);
}

public String getRg()
{
    return rgFormattedTextField.getText();
}

public void setRg(String novoRg)
{
    rgFormattedTextField.setText(novoRg);
}

public String getCpf()
{
    return cpfFormattedTextField.getText();
}

public void setCpf(String novoCpf)
{
    cpfFormattedTextField.setText(novoCpf);
}

public String getEstadoCivil()
{
    return estadoCivilComboBox.getSelectedItem().toString();
}

public void setEstadoCivil(String novoEstado)
{
    estadoCivilComboBox.setSelectedItem(novoEstado);
}

public String getTelefone()
{
    return telefoneFormattedTextField.getText();
}

public void setTelefone(String novoTelefone)
{
    telefoneFormattedTextField.setText(novoTelefone);
}

public String getCargo()
{
    return cargoComboBox.getSelectedItem().toString();
}

public void setCargo(String novoCargo)
{
    cargoComboBox.setSelectedItem(novoCargo);
}

public String getSalario()
{
    return salarioFormattedTextField.getText();
}

public void setSalario(String novoSalario)
{
    salarioFormattedTextField.setText(novoSalario);
}

public void setListaFuncionariosCadastrados(DefaultListModel lista)
{
    listaCadastrosList.setModel(lista);
}


    /**
    * @param args the command line arguments
    */
    /*public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuCadastroFuncionario().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atualizarButton;
    private javax.swing.JLabel cadastroFuncionarioLabel;
    private javax.swing.JLabel camposPreenchidosLabel;
    private javax.swing.JComboBox cargoComboBox;
    private javax.swing.JLabel cargoLabel;
    private javax.swing.JFormattedTextField cpfFormattedTextField;
    private javax.swing.JLabel cpfLabel;
    private javax.swing.JButton criarCadastroButton;
    private javax.swing.JPanel dadosFuncionarioPanel;
    private javax.swing.JLabel enderecoLabel;
    private javax.swing.JTextField enderecoTextField;
    private javax.swing.JComboBox estadoCivilComboBox;
    private javax.swing.JLabel estadoCivilLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JList listaCadastrosList;
    private javax.swing.JPanel menuCadastroFuncionarioPanel;
    private javax.swing.JLabel nomeLabel;
    private javax.swing.JTextField nomeTextField;
    private javax.swing.JButton okButton;
    private javax.swing.JPanel painelCadastrosEfetuadosPanel;
    private javax.swing.JButton removerButton;
    private javax.swing.JFormattedTextField rgFormattedTextField;
    private javax.swing.JLabel rgLabel;
    private javax.swing.JFormattedTextField salarioFormattedTextField;
    private javax.swing.JLabel salarioLabel;
    private javax.swing.JFormattedTextField telefoneFormattedTextField;
    private javax.swing.JLabel telefoneLabel;
    // End of variables declaration//GEN-END:variables

}
