/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ConsultaConta.java
 *
 * Created on 26/11/2008, 21:26:42
 */

package sistemarestaurante;

import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.ListModel;

/**
 *
 * @author edamiani
 */
public class MenuConsultaConta extends javax.swing.JFrame {

    private static MenuConsultaConta menuConsulta = null;
    private ControleContas controleContas;
    /** Creates new form ConsultaConta */
    public MenuConsultaConta() {
        initComponents();
        this.controleContas = new ControleContas(this);
        //centralizarInterface(this);
        getContas();
        
    }
    
    public static MenuConsultaConta getInstancia()
    {
        if (menuConsulta == null)
            menuConsulta = new MenuConsultaConta();
        return menuConsulta;
    }
    
    public static void centralizarInterface(javax.swing.JFrame janela) {  
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        int componentWidth = janela.getWidth();
        int componentHeight = janela.getHeight();
        janela.setBounds((screenSize.width-componentWidth)/2, (screenSize.height-componentHeight)/2, componentWidth, componentHeight);
    }

    public void getContas()
    {
        controleContas.consultaTodasContas();
    }

    public JTextArea getProdutosDaContaTextArea() {
        return produtosDaContaTextArea;
    }



    public void setContasCadastradasList(DefaultListModel lista)
    {
        contasCadastradasList.setModel(lista);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        consultaContasPanel = new javax.swing.JPanel();
        consultaContasLabel = new javax.swing.JLabel();
        consultarContasPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        contasCadastradasList = new javax.swing.JList();
        removerContaButton = new javax.swing.JButton();
        produtosConsumidosPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        produtosDaContaTextArea = new javax.swing.JTextArea();
        okButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SGR - Consulta Contas");
        setResizable(false);

        consultaContasPanel.setBackground(new java.awt.Color(0, 51, 51));
        consultaContasPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 153, 0), 2));

        consultaContasLabel.setFont(new java.awt.Font("Tahoma", 1, 18));
        consultaContasLabel.setForeground(new java.awt.Color(255, 255, 255));
        consultaContasLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        consultaContasLabel.setText("Consulta Contas");

        consultarContasPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 153, 0)), "Consultar Contas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(51, 153, 0))); // NOI18N
        consultarContasPanel.setOpaque(false);

        contasCadastradasList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                contasCadastradasListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(contasCadastradasList);

        removerContaButton.setText("Remover Conta");
        removerContaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerContaButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout consultarContasPanelLayout = new javax.swing.GroupLayout(consultarContasPanel);
        consultarContasPanel.setLayout(consultarContasPanelLayout);
        consultarContasPanelLayout.setHorizontalGroup(
            consultarContasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(consultarContasPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(consultarContasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(removerContaButton)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        consultarContasPanelLayout.setVerticalGroup(
            consultarContasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(consultarContasPanelLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(removerContaButton)
                .addContainerGap(4, Short.MAX_VALUE))
        );

        produtosConsumidosPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 153, 0)), "Produtos da Conta", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(51, 153, 0))); // NOI18N
        produtosConsumidosPanel.setOpaque(false);

        produtosDaContaTextArea.setColumns(20);
        produtosDaContaTextArea.setEditable(false);
        produtosDaContaTextArea.setLineWrap(true);
        produtosDaContaTextArea.setRows(5);
        produtosDaContaTextArea.setWrapStyleWord(true);
        jScrollPane2.setViewportView(produtosDaContaTextArea);

        javax.swing.GroupLayout produtosConsumidosPanelLayout = new javax.swing.GroupLayout(produtosConsumidosPanel);
        produtosConsumidosPanel.setLayout(produtosConsumidosPanelLayout);
        produtosConsumidosPanelLayout.setHorizontalGroup(
            produtosConsumidosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(produtosConsumidosPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                .addContainerGap())
        );
        produtosConsumidosPanelLayout.setVerticalGroup(
            produtosConsumidosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(produtosConsumidosPanelLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                .addContainerGap())
        );

        okButton.setText("OK");
        okButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                okButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout consultaContasPanelLayout = new javax.swing.GroupLayout(consultaContasPanel);
        consultaContasPanel.setLayout(consultaContasPanelLayout);
        consultaContasPanelLayout.setHorizontalGroup(
            consultaContasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(consultaContasPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(consultaContasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(consultaContasPanelLayout.createSequentialGroup()
                        .addComponent(consultarContasPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(consultaContasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(okButton)
                            .addComponent(produtosConsumidosPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(consultaContasLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 722, Short.MAX_VALUE))
                .addContainerGap())
        );
        consultaContasPanelLayout.setVerticalGroup(
            consultaContasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(consultaContasPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(consultaContasLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(consultaContasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(consultaContasPanelLayout.createSequentialGroup()
                        .addComponent(produtosConsumidosPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(okButton))
                    .addComponent(consultarContasPanel, 0, 339, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(consultaContasPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(consultaContasPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void removerContaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerContaButtonActionPerformed
        // TODO add your handling code here:
        if (!contasCadastradasList.isSelectionEmpty())
        {
            int option = JOptionPane.showConfirmDialog(null, "Aviso: Voc� est� prestes a remover um registro de Conta!" +
                " Deseja remover assim mesmo?", "Cuidado!", JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE);
            if (option == 0)
                controleContas.removeConta(contasCadastradasList.getSelectedValue().toString());
            getContas();
        }
}//GEN-LAST:event_removerContaButtonActionPerformed

    private void contasCadastradasListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_contasCadastradasListValueChanged
        // TODO add your handling code here:
        controleContas.buscaProdutosConta(contasCadastradasList.getSelectedValue().toString());
    }//GEN-LAST:event_contasCadastradasListValueChanged

    private void okButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_okButtonMouseClicked
        // TODO add your handling code here:
        getProdutosDaContaTextArea().setText("");
        dispose();
    }//GEN-LAST:event_okButtonMouseClicked

    /**
    * @param args the command line arguments
    */
    /*public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuConsultaConta().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel consultaContasLabel;
    private javax.swing.JPanel consultaContasPanel;
    private javax.swing.JPanel consultarContasPanel;
    private javax.swing.JList contasCadastradasList;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton okButton;
    private javax.swing.JPanel produtosConsumidosPanel;
    private javax.swing.JTextArea produtosDaContaTextArea;
    private javax.swing.JButton removerContaButton;
    // End of variables declaration//GEN-END:variables

}
