/*
 * MenuMesaOcupada.java
 *
 * Created on 13 de Outubro de 2008, 14:48
 */

package sistemarestaurante;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import static sistemarestaurante.FrameUtils.centralizarInterface;
/**
 *
 * @author  Usu�rio
 */
public class MenuMesaOcupada extends javax.swing.JFrame {

    private ArrayList<Mesa> mesasVinculadas;
    private DefaultListModel numeroMesasVinculadas;
    private int numControle;
    private ControleMesa controle;
    private InterfaceInternaCentral inter;
    private static MenuMesaOcupada instancia = null;
    private Ocupacao ocupacao;
    private MenuVenda menuConta;
    
    /** Creates new form MenuMesaOcupada */
    private MenuMesaOcupada(int numControle, ControleMesa controleMesa, 
            Ocupacao ocupacao) 
    {
        initComponents();
        centralizarInterface(this);
        this.mesasVinculadas = new ArrayList<Mesa>();
        this.numeroMesasVinculadas = new DefaultListModel();
        this.numControle = numControle;
        this.controle = controleMesa;
        this.ocupacao = ocupacao;
    }

    public DefaultListModel getNumeroMesasVinculadas() {
        return numeroMesasVinculadas;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuMesaOcupadaPanel = new javax.swing.JPanel();
        mesaOcupadaLabel = new javax.swing.JLabel();
        numeroMesaLabel = new javax.swing.JLabel();
        numeroMesaTextField = new javax.swing.JTextField();
        numeroOcupantesLabel = new javax.swing.JLabel();
        numeroOcupantesTextField = new javax.swing.JTextField();
        tornarLivreButton = new javax.swing.JButton();
        acessarContaButton = new javax.swing.JButton();
        okButton = new javax.swing.JButton();
        horarioOcupacaoLabel = new javax.swing.JLabel();
        horarioOcupacaoFormattedTextField = new javax.swing.JFormattedTextField();
        horarioSaidaLabel = new javax.swing.JLabel();
        horarioSaidaFormattedTextField = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Mesa Ocupada");
        setResizable(false);

        menuMesaOcupadaPanel.setBackground(new java.awt.Color(0, 51, 51));
        menuMesaOcupadaPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 0), 2, true));

        mesaOcupadaLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        mesaOcupadaLabel.setForeground(new java.awt.Color(204, 0, 51));
        mesaOcupadaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mesaOcupadaLabel.setText("A Mesa está Ocupada");

        numeroMesaLabel.setForeground(new java.awt.Color(255, 255, 255));
        numeroMesaLabel.setText("Número da Mesa:");

        numeroMesaTextField.setEditable(false);
        numeroMesaTextField.setColumns(3);
        numeroMesaTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        numeroOcupantesLabel.setForeground(new java.awt.Color(255, 255, 255));
        numeroOcupantesLabel.setText("Número de Ocupantes:");

        numeroOcupantesTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeroOcupantesTextFieldActionPerformed(evt);
            }
        });

        tornarLivreButton.setText("Tornar Livre");
        tornarLivreButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tornarLivreButtonActionPerformed(evt);
            }
        });

        acessarContaButton.setText("Acessar Conta");
        acessarContaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acessarContaButtonActionPerformed(evt);
            }
        });

        okButton.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.highlight"));
        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        horarioOcupacaoLabel.setForeground(new java.awt.Color(255, 255, 255));
        horarioOcupacaoLabel.setText("Horário de Ocupação:");

        horarioOcupacaoFormattedTextField.setEditable(false);
        horarioOcupacaoFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getTimeInstance(java.text.DateFormat.SHORT))));
        horarioOcupacaoFormattedTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        horarioSaidaLabel.setForeground(new java.awt.Color(255, 255, 255));
        horarioSaidaLabel.setText("Horário de Saída (hh:mm):");

        horarioSaidaFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getTimeInstance(java.text.DateFormat.SHORT))));
        horarioSaidaFormattedTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout menuMesaOcupadaPanelLayout = new javax.swing.GroupLayout(menuMesaOcupadaPanel);
        menuMesaOcupadaPanel.setLayout(menuMesaOcupadaPanelLayout);
        menuMesaOcupadaPanelLayout.setHorizontalGroup(
            menuMesaOcupadaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuMesaOcupadaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menuMesaOcupadaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(menuMesaOcupadaPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(okButton))
                    .addComponent(acessarContaButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tornarLivreButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mesaOcupadaLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(menuMesaOcupadaPanelLayout.createSequentialGroup()
                        .addGroup(menuMesaOcupadaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(horarioSaidaLabel)
                            .addComponent(numeroMesaLabel)
                            .addComponent(numeroOcupantesLabel)
                            .addComponent(horarioOcupacaoLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(menuMesaOcupadaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(horarioOcupacaoFormattedTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(horarioSaidaFormattedTextField)
                            .addGroup(menuMesaOcupadaPanelLayout.createSequentialGroup()
                                .addComponent(numeroMesaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(numeroOcupantesTextField, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(282, 282, 282))
        );
        menuMesaOcupadaPanelLayout.setVerticalGroup(
            menuMesaOcupadaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuMesaOcupadaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mesaOcupadaLabel)
                .addGap(19, 19, 19)
                .addGroup(menuMesaOcupadaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numeroMesaLabel)
                    .addComponent(numeroMesaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(menuMesaOcupadaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numeroOcupantesLabel)
                    .addComponent(numeroOcupantesTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(menuMesaOcupadaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(horarioOcupacaoFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(horarioOcupacaoLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(menuMesaOcupadaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(horarioSaidaLabel)
                    .addComponent(horarioSaidaFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tornarLivreButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(acessarContaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(okButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuMesaOcupadaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 318, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuMesaOcupadaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void numeroOcupantesTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeroOcupantesTextFieldActionPerformed
// TODO add your handling code here:
    
}//GEN-LAST:event_numeroOcupantesTextFieldActionPerformed

private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
// TODO add your handling code here:
    ocupacao.setHorarioOcupacao(getHorarioOcupacao());
    ocupacao.setHorarioSaida(getHorarioSaida());
    ocupacao.setNumeroOcupantes(getNumOcupantes());
    this.dispose();
}//GEN-LAST:event_okButtonActionPerformed

private void acessarContaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acessarContaButtonActionPerformed
    // TODO add your handling code here:
    ocupacao.setHorarioOcupacao(getHorarioOcupacao());
    ocupacao.setHorarioSaida(getHorarioSaida());
    ocupacao.setNumeroOcupantes(getNumOcupantes());
    menuConta = new MenuVenda(this.ocupacao);
    menuConta.setVisible(true);
}//GEN-LAST:event_acessarContaButtonActionPerformed

    private void tornarLivreButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tornarLivreButtonActionPerformed
        inter = InterfaceInternaCentral.getInstancia();
        inter.ocupadaParaLivre(controle);
        dispose();
    }//GEN-LAST:event_tornarLivreButtonActionPerformed

    /**
    * @param args the command line arguments
    */
    /*public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuMesaOcupada().setVisible(true);
            }
        });
    }*/

    public static MenuMesaOcupada getInstancia(int numControle, ControleMesa controleMesa, Ocupacao ocupacao, DefaultListModel lista)
    {
        //if (instancia == null)
        
            instancia = new MenuMesaOcupada(numControle, controleMesa, ocupacao);
            instancia.setControle(controleMesa);
            instancia.setNumControle(numControle);
            instancia.horarioOcupacaoFormattedTextField.setText(ocupacao.getHorarioOcupacao());
        return instancia;
    }
    
    public void setControle(ControleMesa controle) {
        this.controle = controle;
    }

    public int getNumOcupantes()
    {
        if (numeroOcupantesTextField.getText().equals(""))
            return 0;
        return Integer.parseInt(numeroOcupantesTextField.getText());
    }

    public String getHorarioOcupacao()
    {
        return horarioOcupacaoFormattedTextField.getText();
    }

    public String getHorarioSaida()
    {
        return horarioSaidaFormattedTextField.getText();
    }

    public void setNumControle(int numControle) {
        this.numControle = numControle;
    }

    public void setNumMesaTextField(String novoValor)
    {
        numeroMesaTextField.setText(novoValor);
    }

    public void setHorarioOcupacaoTextField(String novoValor)
    {
        horarioOcupacaoFormattedTextField.setText(ocupacao.getHorarioOcupacao());
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acessarContaButton;
    private javax.swing.JFormattedTextField horarioOcupacaoFormattedTextField;
    private javax.swing.JLabel horarioOcupacaoLabel;
    private javax.swing.JFormattedTextField horarioSaidaFormattedTextField;
    private javax.swing.JLabel horarioSaidaLabel;
    private javax.swing.JPanel menuMesaOcupadaPanel;
    private javax.swing.JLabel mesaOcupadaLabel;
    private javax.swing.JLabel numeroMesaLabel;
    private javax.swing.JTextField numeroMesaTextField;
    private javax.swing.JLabel numeroOcupantesLabel;
    private javax.swing.JTextField numeroOcupantesTextField;
    private javax.swing.JButton okButton;
    private javax.swing.JButton tornarLivreButton;
    // End of variables declaration//GEN-END:variables

}